package com.servlet;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.Servlet;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;

public class FirstServlet implements Servlet{
	ServletConfig conf;
	
	public void init(ServletConfig args0) throws ServletException{
		this.conf = args0;
		System.out.println("Init method is calling : .....");
	}
	public void service(ServletRequest args0, ServletResponse args1) throws ServletException, IOException{
		args1.setContentType("text/html");
		PrintWriter out = args1.getWriter();
		
		out.print("Hello world ....");
		out.println("making change in servlet ");
		System.out.println("Service method is calling : ....");
	}
	public void destroy() {
		System.out.println("Destroy method is calling : ......");
	}
	public ServletConfig getServletConfig() {
		return this.conf;
	}
	public String getServletInfo() {
		return "This servlet is generated by Sumit singh ......";
	}

}
